#!/bin/bash

# Vercel Environment Variables Setup Script
# Add these manually in Vercel Dashboard:
# https://vercel.com/nathimike102s-projects/payment-gateway-h9/settings/environment-variables

echo "📝 Environment Variables to Add on Vercel Dashboard"
echo "======================================================"
echo ""
echo "1. DATABASE_URL (Production)"
echo "   postgresql://neondb_owner:npg_kW34ztLTHmNf@ep-shy-rain-a7ryhy0v-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
echo ""
echo "2. REDIS_URL (Production)"
echo "   redis://default:ATlJAAIncDE3NTk4OGFmODZhNDk0MTQ3OTRhM2ExOTFlMWZjMGYyNXAxMTQ2NjU@fluent-lobster-14665.upstash.io:6379"
echo ""
echo "3. NODE_ENV (Production)"
echo "   production"
echo ""
echo "4. TEST_MODE (Production)"
echo "   false"
echo ""
echo "5. TEST_PAYMENT_SUCCESS (Production)"
echo "   true"
echo ""
echo "6. TEST_PROCESSING_DELAY (Production)"
echo "   1000"
echo ""
echo "7. TEST_MERCHANT_EMAIL (Production)"
echo "   test@example.com"
echo ""
echo "8. TEST_API_KEY (Production)"
echo "   key_test_abc123"
echo ""
echo "9. TEST_API_SECRET (Production)"
echo "   secret_test_xyz789"
echo ""
echo "======================================================"
echo ""
echo "After adding all variables on Vercel Dashboard:"
echo "1. Go to https://vercel.com/nathimike102s-projects/payment-gateway-h9/settings/environment-variables"
echo "2. Click 'Add' for each variable above"
echo "3. Run: vercel deploy --prod"
echo ""
