const ERROR_CODES = {
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
    BAD_REQUEST_ERROR: 'BAD_REQUEST_ERROR',
    NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
    INVALID_VPA: 'INVALID_VPA',
    INVALID_CARD: 'INVALID_CARD',
    EXPIRED_CARD: 'EXPIRED_CARD',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    SERVER_ERROR: 'SERVER_ERROR',
};

module.exports = ERROR_CODES;
